# Stage 1: Build the app
FROM eclipse-temurin:21-jdk as builder
WORKDIR /app
COPY . .
RUN ./mvnw -B -DskipTests clean package

# Stage 2: Run the app
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copy the built jar (explicitly)
COPY --from=builder /app/target/Tuneup.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
